apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: streamsets.media.example.com
spec:
  group: media.example.com
  scope: Namespaced
  names:
    plural: streamsets
    singular: streamset
    kind: StreamSet
    shortNames:
      - ss
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                urls:
                  type: array
                  items:
                    type: string
                fingerprints:
                  type: array
                  items:
                    type: string
                hlsEnabled:
                  type: boolean
                instanceSize:
                  type: integer
                loaderImage:
                  type: string
                mediamtxImage:
                  type: string
            status:
              type: object
              properties:
                instances:
                  type: integer
                assignments:
                  type: array
                  items:
                    type: object
                    properties:
                      instanceName:
                        type: string
                      urls:
                        type: array
                        items:
                          type: string
